
var webpParser = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(webpParser) {
  webpParser = webpParser || {};


var b;b||(b=typeof webpParser !== 'undefined' ? webpParser : {});var n=Object.assign,p,q;b.ready=new Promise(function(a,c){p=a;q=c});var aa=n({},b),ba="object"===typeof window,v="function"===typeof importScripts,w="",x,y,A,fs,B,C;
if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)w=v?require("path").dirname(w)+"/":__dirname+"/",C=()=>{B||(fs=require("fs"),B=require("path"))},x=function(a,c){C();a=B.normalize(a);return fs.readFileSync(a,c?null:"utf8")},A=a=>{a=x(a,!0);a.buffer||(a=new Uint8Array(a));return a},y=(a,c,f)=>{C();a=B.normalize(a);fs.readFile(a,function(d,e){d?f(d):c(e.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",function(a){throw a;}),b.inspect=function(){return"[Emscripten Module object]"};else if(ba||v)v?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),_scriptDir&&(w=_scriptDir),w=0!==w.indexOf("blob:")?w.substr(0,w.replace(/[?#].*/,"").lastIndexOf("/")+1):"",x=a=>{var c=new XMLHttpRequest;c.open("GET",a,!1);c.send(null);return c.responseText},v&&(A=a=>{var c=new XMLHttpRequest;
c.open("GET",a,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),y=(a,c,f)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?c(d.response):f()};d.onerror=f;d.send(null)};b.print||console.log.bind(console);var D=b.printErr||console.warn.bind(console);n(b,aa);aa=null;var ca=[],E,F;b.wasmBinary&&(F=b.wasmBinary);var noExitRuntime=b.noExitRuntime||!0;"object"!==typeof WebAssembly&&G("no native wasm support detected");
var da,ea=!1;
function fa(a,c,f,d){var e={string:function(h){var z=0;if(null!==h&&void 0!==h&&0!==h){var t=(h.length<<2)+1;z=H(t);var l=z,u=I;if(0<t){t=l+t-1;for(var K=0;K<h.length;++K){var k=h.charCodeAt(K);if(55296<=k&&57343>=k){var va=h.charCodeAt(++K);k=65536+((k&1023)<<10)|va&1023}if(127>=k){if(l>=t)break;u[l++]=k}else{if(2047>=k){if(l+1>=t)break;u[l++]=192|k>>6}else{if(65535>=k){if(l+2>=t)break;u[l++]=224|k>>12}else{if(l+3>=t)break;u[l++]=240|k>>18;u[l++]=128|k>>12&63}u[l++]=128|k>>6&63}u[l++]=128|k&63}}u[l]=
0}}return z},array:function(h){var z=H(h.length);ia.set(h,z);return z}};a=b["_"+a];var g=[],r=0;if(d)for(var m=0;m<d.length;m++){var ha=e[f[m]];ha?(0===r&&(r=ja()),g[m]=ha(d[m])):g[m]=d[m]}f=a.apply(null,g);return f=function(h){0!==r&&ka(r);return"string"===c?J(h):"boolean"===c?!!h:h}(f)}var la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function J(a){if(a){for(var c=I,f=a+void 0,d=a;c[d]&&!(d>=f);)++d;if(16<d-a&&c.subarray&&la)a=la.decode(c.subarray(a,d));else{for(f="";a<d;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))f+=String.fromCharCode((e&31)<<6|g);else{var r=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|r:(e&7)<<18|g<<12|r<<6|c[a++]&63;65536>e?f+=String.fromCharCode(e):(e-=65536,f+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else f+=String.fromCharCode(e)}a=f}}else a="";return a}var ia,I,L,ma=[],M=[],na=[],oa=!1;
function pa(){var a=b.preRun.shift();ma.unshift(a)}var N=0,O=null,P=null;b.preloadedImages={};b.preloadedAudios={};function G(a){if(b.onAbort)b.onAbort(a);a="Aborted("+a+")";D(a);ea=!0;a=new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");q(a);throw a;}function qa(){return Q.startsWith("data:application/octet-stream;base64,")}var Q;Q="webp-parser.wasm.wasm";if(!qa()){var ra=Q;Q=b.locateFile?b.locateFile(ra,w):w+ra}
function sa(){var a=Q;try{if(a==Q&&F)return new Uint8Array(F);if(A)return A(a);throw"both async and sync fetching of the wasm failed";}catch(c){G(c)}}
function ta(){if(!F&&(ba||v)){if("function"===typeof fetch&&!Q.startsWith("file://"))return fetch(Q,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Q+"'";return a.arrayBuffer()}).catch(function(){return sa()});if(y)return new Promise(function(a,c){y(Q,function(f){a(new Uint8Array(f))},c)})}return Promise.resolve().then(function(){return sa()})}
function R(a){for(;0<a.length;){var c=a.shift();if("function"==typeof c)c(b);else{var f=c.B;"number"===typeof f?void 0===c.v?S(f)():S(f)(c.v):f(void 0===c.v?null:c.v)}}}var T=[];function S(a){var c=T[a];c||(a>=T.length&&(T.length=a+1),T[a]=c=L.get(a));return c}var ua={a:function(a,c,f,d){G("Assertion failed: "+J(a)+", at: "+[c?J(c):"unknown filename",f,d?J(d):"unknown function"])},c:function(a,c,f){I.copyWithin(a,c,c+f)},b:function(){G("OOM")}};
(function(){function a(e){b.asm=e.exports;da=b.asm.d;e=da.buffer;b.HEAP8=ia=new Int8Array(e);b.HEAP16=new Int16Array(e);b.HEAP32=new Int32Array(e);b.HEAPU8=I=new Uint8Array(e);b.HEAPU16=new Uint16Array(e);b.HEAPU32=new Uint32Array(e);b.HEAPF32=new Float32Array(e);b.HEAPF64=new Float64Array(e);L=b.asm.k;M.unshift(b.asm.e);N--;b.monitorRunDependencies&&b.monitorRunDependencies(N);0==N&&(null!==O&&(clearInterval(O),O=null),P&&(e=P,P=null,e()))}function c(e){a(e.instance)}function f(e){return ta().then(function(g){return WebAssembly.instantiate(g,
d)}).then(function(g){return g}).then(e,function(g){D("failed to asynchronously prepare wasm: "+g);G(g)})}var d={a:ua};N++;b.monitorRunDependencies&&b.monitorRunDependencies(N);if(b.instantiateWasm)try{return b.instantiateWasm(d,a)}catch(e){return D("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return F||"function"!==typeof WebAssembly.instantiateStreaming||qa()||Q.startsWith("file://")||"function"!==typeof fetch?f(c):fetch(Q,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(c,function(g){D("wasm streaming compile failed: "+g);D("falling back to ArrayBuffer instantiation");return f(c)})})})().catch(q);return{}})();b.___wasm_call_ctors=function(){return(b.___wasm_call_ctors=b.asm.e).apply(null,arguments)};b._webpGetInfo=function(){return(b._webpGetInfo=b.asm.f).apply(null,arguments)};b._webpDecode=function(){return(b._webpDecode=b.asm.g).apply(null,arguments)};
var wa=b._emscripten_bind_VoidPtr___destroy___0=function(){return(wa=b._emscripten_bind_VoidPtr___destroy___0=b.asm.h).apply(null,arguments)},xa=b._emscripten_enum_placeholderToBuild_DO_THING=function(){return(xa=b._emscripten_enum_placeholderToBuild_DO_THING=b.asm.i).apply(null,arguments)},ya=b._emscripten_enum_placeholderToBuild_DO_NOTHING=function(){return(ya=b._emscripten_enum_placeholderToBuild_DO_NOTHING=b.asm.j).apply(null,arguments)};
b._malloc=function(){return(b._malloc=b.asm.l).apply(null,arguments)};var ja=b.stackSave=function(){return(ja=b.stackSave=b.asm.m).apply(null,arguments)},ka=b.stackRestore=function(){return(ka=b.stackRestore=b.asm.n).apply(null,arguments)},H=b.stackAlloc=function(){return(H=b.stackAlloc=b.asm.o).apply(null,arguments)};b.cwrap=function(a,c,f,d){f=f||[];var e=f.every(function(g){return"number"===g});return"string"!==c&&e&&!d?b["_"+a]:function(){return fa(a,c,f,arguments)}};
b.addFunction=function(a,c){if(!E){E=new WeakMap;for(var f=L.length,d=0;d<0+f;d++){var e=S(d);e&&E.set(e,d)}}if(E.has(a))return E.get(a);if(ca.length)f=ca.pop();else{try{L.grow(1)}catch(m){if(!(m instanceof RangeError))throw m;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}f=L.length-1}try{d=f,L.set(d,a),T[d]=a}catch(m){if(!(m instanceof TypeError))throw m;if("function"===typeof WebAssembly.Function){e={i:"i32",j:"i64",f:"f32",d:"f64"};var g={parameters:[],results:"v"==c[0]?[]:[e[c[0]]]};
for(d=1;d<c.length;++d)g.parameters.push(e[c[d]]);d=new WebAssembly.Function(g,a)}else{e=[1,0,1,96];g=c.slice(0,1);c=c.slice(1);var r={i:127,j:126,f:125,d:124};e.push(c.length);for(d=0;d<c.length;++d)e.push(r[c[d]]);"v"==g?e.push(0):e=e.concat([1,r[g]]);e[1]=e.length-2;c=new Uint8Array([0,97,115,109,1,0,0,0].concat(e,[2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0]));c=new WebAssembly.Module(c);d=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f}c=f;L.set(c,d);T[c]=d}E.set(a,f);return f};var U;
P=function za(){U||V();U||(P=za)};
function V(){function a(){if(!U&&(U=!0,b.calledRun=!0,!ea)){oa=!0;R(M);p(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var c=b.postRun.shift();na.unshift(c)}R(na)}}if(!(0<N)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)pa();R(ma);0<N||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=V;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();V();function W(){}W.prototype=Object.create(W.prototype);W.prototype.constructor=W;W.prototype.u=W;W.A={};b.WrapperObject=W;function X(a){return(a||W).A}b.getCache=X;function Y(a,c){var f=X(c),d=f[a];if(d)return d;d=Object.create((c||W).prototype);d.s=a;return f[a]=d}b.wrapPointer=Y;b.castObject=function(a,c){return Y(a.s,c)};b.NULL=Y(0);
b.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete X(a.u)[a.s]};b.compare=function(a,c){return a.s===c.s};b.getPointer=function(a){return a.s};b.getClass=function(a){return a.u};function Z(){throw"cannot construct a VoidPtr, no constructor in IDL";}Z.prototype=Object.create(W.prototype);Z.prototype.constructor=Z;Z.prototype.u=Z;Z.A={};b.VoidPtr=Z;Z.prototype.__destroy__=function(){wa(this.s)};
(function(){function a(){b.DO_THING=xa();b.DO_NOTHING=ya()}oa?a():M.unshift(a)})();


  return webpParser.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = webpParser;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return webpParser; });
else if (typeof exports === 'object')
  exports["webpParser"] = webpParser;
